MODEL:
  META_ARCHITECTURE: "Toy"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  CLS:
    IN_FEATURES: ["res3"]
    STRIDES: [8]
    NUM_CLASSES: 1
    EXPAND_BG: False
    USE_SIGMOID: True
    USE_SOFTMAX: False
VERSION: 2