MODEL:
  NAME: toy
  NUM_CLASSES: 1
  USE_SIGMOID: False
  LOSS_FUN: bce_logits
  BACKBONE:
    NAME: resnet
    DEPTH: 50
    OUT_INDICES: [1, 2, 3, 4]
  NECK:
    NAME: fpn
    IN_CHANNELS: [256, 512, 1024, 2048]
    OUT_CHANNELS: 256
    OUT_INDICES: [1]
    STRIDES: [8]
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.2
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
TRAIN:
  DATASET: toy
  IM_SIZE: 256
  BATCH_SIZE: 16
TEST:
  DATASET: toy
  IM_SIZE: 256
  BATCH_SIZE: 16
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .